site_name: MACAPP
site_url: https://darwinyusef.github.io/materialmkdocs/
site_author: Yusef Gonzalez | Aquicreamos
site_description: >-
  Este es un proyecto que gestiona la documentación de mi proyecto – 
  contiene los datos de usuario y contenidos

# Repository
repo_name: darwinyusef/materialmkdocs
repo_url: https://github.com/darwinyusef/materialmkdocs

# Copyright
copyright: Copyright &copy; 2024 - 2030 Yusef Gonzalez | Aquicreamos

extra_css:
  - assets/css/style.css

extra_javascript:
  - assets/js/script.js

theme:
  name: material
  extra_css: style.css
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra:
  status:
    new: Recently added
    deprecated: Active
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/darwinyusef
    - icon: fontawesome/brands/golang
      link: https://github.com/darwinyusef
    - icon: fontawesome/brands/react
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/whatsapp
      link: https://web.whatsapp.com/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Análisis de Software:
      - MACP-2 Menú principal: macp-2.md
      - MACP-3 Submenu desplegable: macp-3.md
      - MACP-4 Menú responsivo: macp-4.md
      - MACP-5 acceso rapido: macp-5.md
      - MACP-6 Diseñar enlace carrito compras: macp-6.md
      - MACP-7 slider promocionales: macp-7.md
      - MACP-8 seecion productos destacados: macp-8.md
      - MACP-9 Enlace redes sociales: macp-9.md
      - MACP-10 Barra de busqueda: macp-10.md
      - MACP-11 Comentarios de clientes: macp-11.md
      - MACP-13 Implementar diseño Responsivo: macp-13.md
      - MACP-14 Carga rapida de pagina: macp-14.md
      - MACP-15 Navegación Intuitiva: macp-15.md
      - MACP-16 Ayuda y Soporte Accesible: macp-16.md 
      - MACP-17 Accesibilidad Discapacidades: macp-17.md    
      - MACP-18 Personalización de Interfaz : macp-18.md
      - MACP-19 Breadcrumbs para navegación: macp-19.md
      - MACP-20 Alertas y Notificaciones: macp-20.md
      - MACP-21 Feedback Visual: macp-21.md
      - MACP-22 Zoom en Imagenes: macp-22.md
      - MACP-24 Filtrado de productos: macp-24.md
      - MACP-25 Menús Desplegables: macp-25.md
      - MACP-26 Pagina de detalles de producto: macp-26.md
      - MACP-27 Comentarios y valoracón: macp-27.md
      - MACP-28 Notificaciones de Stock: macp-28.md
      - MACP-30 Registro de usuarios: macp-30.md
      - MACP-31 Recuperación de contraseñas: macp-31.md
      - MACP-32 Crear Perfil de usuario: macp-32.md
      - MACP-33 Editar datos de perfil: macp-33.md
      - MACP-34 cerrar sesión segura: macp-34.md


